#################################################################################
#
#   This is the package for NWS ALERTS USING THE CUSTOM COMPONENT
#
#################################################################################

## For testing the API

# https://api.weather.gov/alerts/active/count

# https://api.weather.gov/alerts/active?zone=INZ009,INC033

########################  SENSOR  ###############################################

## the NWS Sensor can now be ionstalled using HACS. If you use HACS you can remove the nws_alerts sensor from here.

sensor:
  # https://github.com/eracknaphobia/nws_custom_component
  - platform: nws_alerts
    zone_id: 'INZ009,INC033'
  - platform: template
    sensors:
      nws_alerts_are_active:
        friendly_name: NWS Alerts Are Active
        #entity_id: sensor.nws_alerts
        value_template: >
          {% if states('sensor.nws_alerts') | int > 0 %}
            on
          {% else %}
            off
          {% endif %}
        icon_template: >-
          {% if states('sensor.nws_alerts') | int > 0 %}
            mdi:weather-lightning
          {% else %}
            mdi:weather-sunny
          {% endif %}
          
  - platform: weatheralerts
    state: IN
    zone: 9
    county: 33
  

######################## BINARY SENSOR  #########################################

binary_sensor:
  - platform: template
    sensors:
      nws_alerts_are_active:
        friendly_name: NWS Alerts Are Active
        entity_id: sensor.nws_alerts
        value_template: >
          {{ states('sensor.nws_alerts') | int > 0 }}
        icon_template: >-
          {% if states('sensor.nws_alerts') | int > 0 %}
            mdi:weather-lightning
          {% else %}
            mdi:weather-sunny
          {% endif %}
      ## NOT USING THIS SENSOR IN AUTOMATIONS...YET?
      nws_new_alert:
        friendly_name: NWS Alert is New
        entity_id: sensor.nws_alerts
        value_template: >
          {% if  state_attr('sensor.nws_alerts', 'event_id') != None %}
            {{ (state_attr('sensor.nws_alerts', 'event_id').split('-')[0] not in states.variable.nws_alerts_event_ids.attributes.values()|list) 
            and (state_attr('sensor.nws_alerts', 'event_id').split('-')[0] != states('variable.nws_alerts_event_ids')) }}
          {% else %}
            false
          {% endif %}


######################## INPUT BOOLEAN  #########################################

input_boolean:
  nws_multi_alert:
    name: NWS Multiple Alerts At Once    
    
########################  AUTOMATION  ###########################################

automation:
  - alias: 'NWS Check for Multi Alerts'
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: sensor.nws_alerts
    condition:
      - "{{ states('sensor.nws_alerts') | int > 0 }}"
      - '{{ trigger.to_state.state|int > trigger.from_state.state|int }}'
    action:
      - choose:
          - conditions:
              - '{{ (trigger.to_state.state | int - trigger.from_state.state|int) > 1 }}'
            sequence:
              - service: input_boolean.turn_on
                entity_id: input_boolean.nws_multi_alert
              - delay:
                  seconds: 30
              - service: input_boolean.turn_on
                entity_id: input_boolean.nws_multi_alert
          - conditions:
            - '{{ (trigger.to_state.state | int - trigger.from_state.state|int) == 1 }}'
            sequence:
              - service: input_boolean.turn_off
                entity_id: input_boolean.nws_multi_alert
  
  - alias: 'NWS Weather Alert Pop Up Control'
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: sensor.nws_alerts
    condition:
      - "{{ states('sensor.nws_alerts') | int > 0 }}"
      - '{{ trigger.to_state.state|int > trigger.from_state.state|int }}'
      - "{{ (state_attr('sensor.nws_alerts', 'event_id').split('-')[0] not in states.variable.nws_alerts_event_ids.attributes.values()|list) and (state_attr('sensor.nws_alerts', 'event_id').split('-')[0] != states('variable.nws_alerts_event_ids')) }}"
    action:
      - delay:
          seconds: 5
      - choose:
        - conditions:
            - condition: state
              entity_id: input_boolean.nws_multi_alert
              state: 'on'
            - '{{ (trigger.to_state.state | int - trigger.from_state.state|int) == 2 }}'
            - "{{ (state_attr('sensor.nws_alerts', 'event_id').split('-')[1] not in states.variable.nws_alerts_event_ids.attributes.values()|list) and (state_attr('sensor.nws_alerts', 'event_id').split('-')[1] != states('variable.nws_alerts_event_ids')) }}"
          sequence:
            - service: script.nws_popup_on_wx_alert
              data:
                title: >
                  "{{ state_attr('sensor.nws_alerts', 'title').split(' - ')[0] }}"
                message: >
                  "{{ state_attr('sensor.nws_alerts', 'display_desc').split('\n\n-\n\n')[0] }}"
            - service: script.nws_popup_on_wx_alert
              data:
                title: >
                  "{{ state_attr('sensor.nws_alerts', 'title').split(' - ')[1] }}"
                message: >
                  "{{ state_attr('sensor.nws_alerts', 'display_desc').split('\n\n-\n\n')[1] }}"
        - conditions:
            - condition: state
              entity_id: input_boolean.nws_multi_alert
              state: 'on'
            - '{{ (trigger.to_state.state | int - trigger.from_state.state|int) == 3 }}'
            - "{{ (state_attr('sensor.nws_alerts', 'event_id').split('-')[1] not in states.variable.nws_alerts_event_ids.attributes.values()|list) and (state_attr('sensor.nws_alerts', 'event_id').split('-')[1] != states('variable.nws_alerts_event_ids')) }}"
            - "{{ (state_attr('sensor.nws_alerts', 'event_id').split('-')[2] not in states.variable.nws_alerts_event_ids.attributes.values()|list) and (state_attr('sensor.nws_alerts', 'event_id').split('-')[2] != states('variable.nws_alerts_event_ids')) }}"
          sequence:
            - service: script.nws_popup_on_wx_alert
              data:
                title: >
                  "{{ state_attr('sensor.nws_alerts', 'title').split(' - ')[0] }}"
                message: >
                  "{{ state_attr('sensor.nws_alerts', 'display_desc').split('\n\n-\n\n')[0] }}"
            - service: script.nws_popup_on_wx_alert
              data:
                title: >
                  "{{ state_attr('sensor.nws_alerts', 'title').split(' - ')[1] }}"
                message: >
                  "{{ state_attr('sensor.nws_alerts', 'display_desc').split('\n\n-\n\n')[1] }}"
            - service: script.nws_popup_on_wx_alert
              data:
                title: >
                  "{{ state_attr('sensor.nws_alerts', 'title').split(' - ')[2] }}"
                message: >
                  "{{ state_attr('sensor.nws_alerts', 'display_desc').split('\n\n-\n\n')[2] }}"
        default:
          service: script.nws_popup_on_wx_alert
          data:
            title: >
              "{{ state_attr('sensor.nws_alerts', 'title').split(' - ')[0] }}"
            message: >
              "{{ state_attr('sensor.nws_alerts', 'display_desc').split('\n\n-\n\n')[0] }}"
          
  - alias: NWS Notification Weather Alert
    initial_state: 'on'
    trigger:
      platform: state
      entity_id: sensor.nws_alerts
    condition:
      - "{{states('sensor.nws_alerts') | int > 0}}"
      - '{{ trigger.to_state.state|int > trigger.from_state.state|int }}'
      - "{{ (state_attr('sensor.nws_alerts', 'event_id').split('-')[0] not in states.variable.nws_alerts_event_ids.attributes.values()|list) and (state_attr('sensor.nws_alerts', 'event_id').split('-')[0] != states('variable.nws_alerts_event_ids')) }}"
    action:
      - service: notify.pushbullet_notify
        data:
          message: >
            "NWS: {{ state_attr('sensor.nws_alerts', 'title').split(' - ')[0] }}"
            
  - alias: NWS Announce Weather Alert
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: sensor.nws_alerts
    condition:
      condition: and
      conditions:
        - "{{states('sensor.nws_alerts') | int > 0}}"
        - '{{ trigger.to_state.state|int > trigger.from_state.state|int }}'
        - "{{ ('Severe Thunderstorm Warning' in state_attr('sensor.nws_alerts', 'title')) or ('Tornado Warning' in state_attr('sensor.nws_alerts', 'title')) }}"
        - "{{ (state_attr('sensor.nws_alerts', 'event_id').split('-')[0] not in states.variable.nws_alerts_event_ids.attributes.values()|list) and (state_attr('sensor.nws_alerts', 'event_id').split('-')[0] != states('variable.nws_alerts_event_ids')) }}"
    action:
      - service: media_player.volume_set
        data:
          entity_id:
            - media_player.computer_room_dot
            - media_player.kitchen_dot
            - media_player.garage_dot
            - media_player.basement_dot
            - media_player.lg_webos_tv_echo
          volume_level: 0.9
      - service: notify.alexa_media
        data:
          target: 
            - media_player.computer_room_dot
            - media_player.kitchen_dot
            - media_player.garage_dot
            - media_player.basement_dot
            - media_player.lg_webos_tv_echo
          data:
            type: tts
          message: >
            {% if 'Severe Thunderstorm Warning' in state_attr('sensor.nws_alerts', 'title') %}
              Attention!,,,Attention!,,,The National Weather Service Has issued a severe thunderstorm warning for our area
            {% elif 'Tornado Warning' in state_attr('sensor.nws_alerts', 'title') %}
              Attention!,,,Attention!,,,The National Weather Service Has issued a tornado warning for our area
            {% endif %}
      - delay: '00:00:15'
      - service: notify.alexa_media
        data:
          target: 
            - media_player.computer_room_dot
            - media_player.kitchen_dot
            - media_player.garage_dot
            - media_player.basement_dot
            - media_player.lg_webos_tv_echo
          data:
            type: tts
          message: >
            {% if 'Severe Thunderstorm Warning' in state_attr('sensor.nws_alerts', 'title') %}
              Attention!,,,Attention!,,,The National Weather Service Has issued a severe thunderstorm warning for our area
            {% elif 'Tornado Warning' in state_attr('sensor.nws_alerts', 'title') %}
              Attention!,,,Attention!,,,The National Weather Service Has issued a tornado warning for our area
            {% endif %}
                  
  - alias: NWS Announce Weather Alert for MBR
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: sensor.nws_alerts
    condition:
      condition: and
      conditions:
        - "{{states('sensor.nws_alerts') | int > 0}}"
        - "{{ 'Tornado Warning' in state_attr('sensor.nws_alerts', 'title') }}"
        - "{{ (state_attr('sensor.nws_alerts', 'event_id').split('-')[0] not in states.variable.nws_alerts_event_ids.attributes.values()|list)  (state_attr('sensor.nws_alerts', 'event_id').split('-')[0] != states('variable.nws_alerts_event_ids')) }}"
    action:
      - service: media_player.volume_set
        data:
          entity_id:
            - media_player.bedroom_2_dot
            - media_player.master_bedroom_dot
            - media_player.big_room_dot
          volume_level: 0.9
      - service: notify.alexa_media
        data:
          target: 
            - media_player.bedroom_2_dot
            - media_player.master_bedroom_dot
            - media_player.big_room_dot
          data:
            type: tts
          message: "Attention!,,,Attention!,,,The National Weather Service Has issued a Tornado Warning for our area."
      - delay: '00:00:15'
      - service: notify.alexa_media
        data:
          target: 
            - media_player.bedroom_2_dot
            - media_player.master_bedroom_dot
            - media_player.big_room_dot
          data:
            type: tts
          message: "Attention!,,,Attention!,,,The National Weather Service Has issued a Tornado Warning for our area."
              
     
  - alias: NWS Update Event ID Variable
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: sensor.nws_alerts
    action:
      service: variable.set_variable
      data:
        variable: nws_alerts_event_ids
        value: "{{ (trigger.to_state.attributes.event_id).split('-')[0] }}"
        attributes: 
          history_1: "{{ states('variable.nws_alerts_event_ids') }}"
          history_2: "{{ state_attr('variable.nws_alerts_event_ids', 'history_1') }}"
          history_3: "{{ state_attr('variable.nws_alerts_event_ids', 'history_2') }}"
          history_4: "{{ state_attr('variable.nws_alerts_event_ids', 'history_3') }}"
          history_5: "{{ state_attr('variable.nws_alerts_event_ids', 'history_4') }}"
          history_6: "{{ state_attr('variable.nws_alerts_event_ids', 'history_5') }}"
          history_7: "{{ state_attr('variable.nws_alerts_event_ids', 'history_6') }}"
          history_8: "{{ state_attr('variable.nws_alerts_event_ids', 'history_7') }}"
          history_9: "{{ state_attr('variable.nws_alerts_event_ids', 'history_8') }}"
          history_10: "{{ state_attr('variable.nws_alerts_event_ids', 'history_9') }}"
          
        
#################################  SCRIPT  ###################################
          
script:
  nws_popup_on_wx_alert:
    alias: NWS Weather Alert Pop Up
    sequence:
      ## Create a new persistant notification in the UI for a new alert
      - service: >
          {% if states('sensor.nws_alerts') != '0' %}
            persistent_notification.create
          {% endif %}
        data_template:
          notification_id: "nwswxalert"
          message: "{{ message }}"
          title: '{{ title }}'
        
############################## VARIABLE  #####################################

## this uses the hass_variable custom component.
## you can install thru HACS or manually from https://github.com/Wibias/hass-variables

variable:
  nws_alerts_event_ids:
    value: 'none'
    restore: true
