name: CI

on:
  workflow_dispatch:
  push:
  pull_request:
  schedule:
    - cron: "0 7 1-28/7 * *"

jobs:
  validate:
    runs-on: ubuntu-latest
    name: HACS & Hassfest
    steps:
      - uses: actions/checkout@v6
      - uses: hacs/action@main
        with:
          category: integration
      - uses: home-assistant/actions/hassfest@master

  lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
        with:
          python-version: "3.13"
      - run: pip install ruff
      - run: ruff format --check custom_components/ tests/
      - run: ruff check custom_components/ tests/

  typecheck:
    runs-on: ubuntu-latest
    name: Type check
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
        with:
          python-version: "3.13"
      - run: pip install -r requirements_test.txt
      - run: mypy custom_components/nws_alerts

  test:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
        with:
          python-version: "3.13"
      - run: pip install -r requirements_test.txt
      - run: pytest tests
